services:
  ui-dev:
    build:
      context: electron-ui
      dockerfile: Dockerfile.dev
    container_name: ui-dev
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gym-pro
      
  ui-prod:
    build:
      context: electron-ui
      dockerfile: Dockerfile.prod
    container_name: ui-prod
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      tmeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gym-pro

networks:
  gym-pro:
    name: gym-pro